"""Add email field to User

Revision ID: 653454f39b83
Revises: 15dd187ac882
Create Date: 2024-09-24 01:26:50.259762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653454f39b83'
down_revision = '15dd187ac882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('contacto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacto', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
