"""Add Appointment model

Revision ID: aadde20da81d
Revises: bf00ea93e2c6
Create Date: 2024-09-18 01:02:11.312634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadde20da81d'
down_revision = 'bf00ea93e2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
