"""Changed column name from password to password_hash

Revision ID: bb9ab507586c
Revises: 48b44fbf158c
Create Date: 2024-09-27 01:12:44.194398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9ab507586c'
down_revision = '48b44fbf158c'
branch_labels = None
depends_on = None


def upgrade():
    
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=False, server_default='default_hash'))

    # Optionally remove the default value after it's applied
    op.alter_column('user', 'password_hash', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
